---
name: Deploy to DockerHub

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  push:
    branches:
      - main
      - cicd

defaults:
  run:
    working-directory: ./docker

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        run: |
          ./deploy.sh dockerhub
