---
name: Deploy to Azure ACR

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  push:
    branches:
      - main
      - cicd

defaults:
  run:
    working-directory: ./docker

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AZURE_ACR_URL: ${{ secrets.AZURE_ACR_URL }}
  AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and push Docker images
        run: |
          ./deploy.sh azure
