---
name: Terraform Destroy

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  schedule:
    - cron: "0 0 * * FRI"

defaults:
  run:
    working-directory: ./terraform

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  validation_and_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Validate
        run: |
          terraform apply -destroy -auto-approve
